### ISSUE TITLE
Kanta.POWriter.Plugin.FormComponent undefined

### ISSUE THREAD

**Issue by louisvisser** [curiosum-dev/kanta_po_writer_plugin#1]
The last commit - [Remove unused FormComponent file](https://github.com/curiosum-dev/kanta_po_writer_plugin/commit/5e85bccf92ccfb3b9b9276e317bccf212db4d592) - breaks the Kanta UI when viewing a specific translation (ex `kanta/locales/1/translations/1`) with the following error:

```elixir
    ** (UndefinedFunctionError) function Kanta.POWriter.Plugin.FormComponent.__live__/0 is undefined (module Kanta.POWriter.Plugin.FormComponent is not available)
        Kanta.POWriter.Plugin.FormComponent.__live__()
        (kanta 0.1.4) lib/kanta_web/live/translations/translation_form_live/components/singular_translation_form/singular_translation_form.html.heex:81: anonymous fn/3 in KantaWeb.Translations.SingularTranslationForm.render/1
        (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (kanta 0.1.4) lib/kanta_web/live/translations/translation_form_live/components/singular_translation_form/singular_translation_form.html.heex:80: anonymous fn/2 in KantaWeb.Translations.SingularTranslationForm.render/1
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:386: Phoenix.LiveView.Diff.traverse/7
```

Falling back to the previous commit solves the issue:
```elixir
# mix.exs
{:kanta, "~> 0.1.2"},
{:kanta_po_writer_plugin, git: "https://github.com/curiosum-dev/kanta_po_writer_plugin", ref: "7b786bd6dc5ffaf3f37c6c1b72fa41fa9758f74d"}
```

```elixir
# mix.lock
"kanta": {:hex, :kanta, "0.1.4", ...
"kanta_po_writer_plugin": {:git, "https://github.com/curiosum-dev/kanta_po_writer_plugin", "7b786bd6dc5ffaf3f37c6c1b72fa41fa9758f74d", [ref: "7b786bd6dc5ffaf3f37c6c1b72fa41fa9758f74d"]},
```

**Comment by ravensiris** [comment]
`FormComponent` used to be mandatory in kanta. It is no longer the case.
I'd suggest updating kanta first and then trying the newer version.
